### ISSUE TITLE
Spurious warning Folder path Mail/ does not exist

### ISSUE THREAD

**Issue by rhertzog** [rc0/mairix#9] opened 2014-07-31 15:47 UTC
If you have a ~/.mairixrc like this:

```
base=Mail
maildir=...
database=/home/rhertzog/.cache/mairix
```

And if you call "mairix -F" outside of your home directoly, then you get a warning:

```
┏x230-buxy:~/tmp
┗(528)$ mairix -F
WARNING: Folder path Mail/ does not exist
```

This is contrary to what the documentation says:

```
       base=base-directory
              This defines the path to the common parent directory of all your maildir folders.

              If  the  path  is  relative,  it is treated as relative to the location of the mairixrc
              file.
```

**Comment by vandry** [comment] 2017-07-17 19:51
Duplicate of #3

**Closed by vandry** 2017-07-17 19:51 UTC
